### ISSUE TITLE
Project: Getting to know the Butler

### ISSUE THREAD

**Issue by Madejski** [LSSTScienceCollaborations/StackClub#59] opened 2018-07-19 21:58 UTC
This is a new issue, aimed to produce a relatively simple notebook to allow Newbies to get up to speed with Butler, and to use Butler to study properties of images.

**Comment by drphilmarshall** [comment] 2018-07-19 22:15
Great! There should be plenty to go on in the commissioning team examples. You might want to coordinate with @stargaser , who will need a butler to serve up an example calexp or two for his guided tour ( #57 ). Also, you should include using the butler to access the various catalogs too - since the catalogs are where people are most likely to start.

**Comment by drphilmarshall** [comment] 2018-07-19 22:23
PS. Suggest this notebook go in Basics and be entitled "Getting to know the Butler" ;-)

**Comment by Madejski** [comment] 2018-07-19 22:58
Good and catchy suggestion, Phil!  In fact, I was just realizing that what would be super-useful would be some form of links to repositories containing the parameters required by Butler for various data sets.  I am sure this varies from dataset to dataset but there must be some top-level logic...

**Comment by drphilmarshall** [comment] 2018-10-03 19:57
This _might_ be a duplicate of #128 but let's see - it could be that there is room for a guided tour of the Butler's capabilities separate from using the Butler to explore a dataset.

**Comment by drphilmarshall** [comment] 2018-11-19 01:13
I think this project idea is indeed a duplicate of #128 ("Exploring a Data Repository") so am closing this out to keep the project list clean.

**Closed by drphilmarshall** 2018-11-19 01:13 UTC
Labels: Basics, opportunity, project
